-- Supabase PostgreSQL schema for City Grievance Services.
-- Apply this file in the Supabase SQL Editor before deploying the app.

create table if not exists admin (
    id bigint generated by default as identity primary key,
    username varchar(250) not null,
    password varchar(250) not null,
    updationdate varchar(255) not null default ''
);

create table if not exists category (
    id bigint generated by default as identity primary key,
    categoryname varchar(255),
    categorydescription text,
    creationdate timestamptz default current_timestamp,
    updationdate timestamptz
);

create table if not exists complaintremark (
    id bigint generated by default as identity primary key,
    complaintnumber bigint not null,
    status varchar(255) not null,
    remark text not null,
    remarkdate timestamptz not null default current_timestamp
);

create table if not exists state (
    id bigint generated by default as identity primary key,
    statename varchar(255),
    statedescription text,
    postingdate timestamptz default current_timestamp,
    updationdate timestamptz
);

create table if not exists subcategory (
    id bigint generated by default as identity primary key,
    categoryid bigint,
    subcategory varchar(255),
    creationdate timestamptz default current_timestamp,
    updationdate timestamptz
);

create table if not exists tblcomplaints (
    complaintnumber bigint generated by default as identity primary key,
    userid bigint,
    category bigint,
    subcategory varchar(255),
    complainttype varchar(255),
    state varchar(255),
    noc varchar(255),
    complaintdetails text,
    complaintfile varchar(255),
    regdate timestamptz default current_timestamp,
    status varchar(50),
    lastupdationdate timestamptz
);

create table if not exists userlog (
    id bigint generated by default as identity primary key,
    uid bigint not null default 0,
    username varchar(255) not null,
    userip inet,
    logintime timestamptz not null default current_timestamp,
    logout varchar(255) not null default '',
    status integer not null
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    fullname varchar(255),
    useremail varchar(255),
    password varchar(255),
    contactno bigint,
    address text,
    state varchar(255),
    country varchar(255),
    pincode integer,
    userimage varchar(255),
    regdate timestamptz not null default current_timestamp,
    updationdate varchar(255),
    status smallint
);

create index if not exists users_useremail_idx on users (useremail);
create index if not exists tblcomplaints_userid_regdate_idx on tblcomplaints (userid, regdate desc);
create index if not exists tblcomplaints_status_idx on tblcomplaints (status);
create index if not exists complaintremark_complaintnumber_idx on complaintremark (complaintnumber);
create index if not exists subcategory_categoryid_idx on subcategory (categoryid);
create index if not exists userlog_username_id_idx on userlog (username, id desc);

alter table admin enable row level security;
alter table category enable row level security;
alter table complaintremark enable row level security;
alter table state enable row level security;
alter table subcategory enable row level security;
alter table tblcomplaints enable row level security;
alter table userlog enable row level security;
alter table users enable row level security;

revoke all on table admin, category, complaintremark, state, subcategory,
    tblcomplaints, userlog, users from anon, authenticated;

-- Create the first administrator after applying this schema. The existing PHP
-- login currently expects an MD5 digest; replace this with a strong password.
-- insert into admin (username, password, updationdate)
-- values ('admin', md5('replace-with-a-strong-password'), '');